name: CDGitops

on: 
  push:
    branches: [main]    

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # env:
    #   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}    
    #   DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 

    steps:

    - name: Run Commands with a Secret
      env:
          DOCKER_USERNAME: "vicentepf78"
          # ${{ secrets.DOCKER.DOCKER_USERNAME }} + "TESTE"   
          DOCKER_PASSWORD: "dckr_pat_7sehV9JKxGHnmlF8zEItZRKFahc"
          #  ${{ secrets.DOCKER.DOCKER_PASSWORD }} + "TESTE"

      run: |
        echo "Hello World"
        echo "This docker username: $DOCKER_USERNAME"
        echo "This docker password: $DOCKER_PASSWORD"


    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        repository: "vicentepf78/gitopsfc"
        username: "vicentepf78"
        password: "dckr_pat_7sehV9JKxGHnmlF8zEItZRKFahc"   

        # repository: "$DOCKER_USERNAME/gitopsfc"
        # username: "$DOCKER_USERNAME"
        # password: "$DOCKER_PASSWORD"   


    - name: Build and push image to Dockerhub
      uses: docker/build-push-action@v5
      with:
        repository: "vicentepf78/gitopsfc"
        username: "vicentepf78"
        password: "dckr_pat_7sehV9JKxGHnmlF8zEItZRKFahc"   

        # repository: "$DOCKER_USERNAME/gitopsfc"
        # tags: ${{ github.sha }}, latest.
        push: true
        tags: ${{ steps.meta.outputs.tags }}, latest
        labels: ${{ steps.meta.outputs.labels }}